### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by jemacom**

### CODE REVIEW

**Comment by budhrg** [comment]
add to whitelist

**Comment by praveenkumar** [comment]
@jemacom can you add a `addon.remove` file which make sure this addon can be removed using the minishift command line itself instead user go to readme, check the sample https://github.com/minishift/minishift-addons/tree/master/add-ons/che `che.addon.remove` , pretty easy to do.

**Comment by LalatenduMohanty** [comment]
Created https://github.com/minishift/minishift-addons/issues/153 for this PR.

**Comment by LalatenduMohanty** [comment]
Merged https://github.com/minishift/minishift-addons/commit/c43ceaf293c8916033947398048e2a4dc6e53737 thanks @jemacom

**Pull request closed without merging**
