### PR TITLE
RHOAR node.js imagestreams addon

### PR DESCRIPTION
**Pull request by jorgemoralespou**
Adds RHOAR community imagestreams

### CODE REVIEW

**Comment by budhrg** [comment]
@jorgemoralespou Need rebase :)

**Comment by jorgemoralespou** [comment]
@budhrg Rebased. Sorry I missed this

**Comment by praveenkumar** [comment]
looks like still have lot of commits, need rebase.

**Comment by praveenkumar** [comment]
> Rebase or squash?

@jorgemoralespou rebase and squash to the single commit.

**Comment by jorgemoralespou** [comment]
Replaced by https://github.com/minishift/minishift-addons/pull/142

**Pull request closed without merging**
