### PR TITLE
[WIP] Issue #67 Test framework to write tests for the add-ons

### LINKED ISSUE #67: Need a test framework to write tests for the add-ons
The end goal is we should be able to test these add-ons against specific OpenShift and Minishift versions. Contributors should be able to contribute a test file which would test the add-on. Also we should be able to test these add-ons for each Minishift release in an automated way. 

This way we can maintain the quality of the repository and it will enable us to keep the add-ons in good shape.

### PR DESCRIPTION
**Pull request by budhrg**
Fix #67 

This is just the first cut. Feedback is needed.

Tests can be run as:
## Test all
```
$ make test
```

## Test specific
```
$ make test TEST_ADDON_NAME=<addon-name>
```

Eg execution:
```
$ make test
---------
- Testing cors addon
Minishift version: minishift v1.12.0+daa0943
Minishift version: Does Not Exist
Starting Minishift
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ..................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.1
-- Checking `oc` support for startup flags ... 
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.1 ...
Pulling image openshift/origin:v3.6.1
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 85% complete
Pulled 3/4 layers, 97% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.200:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'cors':..
CORS is now allowed from any address

Installing /home/budhram/redhat/minishift-addons/add-ons/cors addon
Add-on installation failed with the error: Addon already exists in target directory '/home/budhram/.minishift/addons/cors'
Applying /home/budhram/redhat/minishift-addons/add-ons/cors addon
Veriying addon apply
Addon apply successful
```

### NOTE: 
It is expected that the maintianer should provide test file inside `tests` dir with name `test_<addon-name>.sh`.

From here on,  it is easy to provide CI #27 

Thoughts @minishift/minishift-dev

### CODE REVIEW

**Comment by praveenkumar** [comment]
I would probably go with that @agajdosi is doing as part of integration test, Once we have a separate binary for a test then it would be easy to integrate.

**Comment by agajdosi** [comment]
I think the integration tests are the ideal way to go. But on the other I understand there are probably some contributors who would prefer the bash scripts. Thus we might consider supporting both ways if that would not bring considerable amount of maintenance costs for us.

**Comment by praveenkumar** [comment]
@agajdosi once we have a template/example around how to write the test case for an addon then it would be not that difficult to follow.

**Comment by budhrg** [comment]
>  once we have a template/example around how to write the test case for an addon then it would be not that difficult to follow.

I still feel we are providing an opinionated way of writing tests to users who don't know Go and can write underline step definition implementation.

**Comment by budhrg** [comment]
Closing it in support of #85 after discussion since having two paths of writing tests add diversion to users.

**Pull request closed without merging**
