### PR TITLE
Using the latest Strimzi images

### PR DESCRIPTION
**Pull request by matzew**
Strimzi is the new kid on the block - Barnabas was renamed, and the 0.1.0 release is used from Strimzi

### CODE REVIEW

**Comment by matzew** [comment]
@jpechane @ppatierno

**Comment by matzew** [comment]
part of https://issues.jboss.org/browse/DBZ-545 

(will send more/different PRs)

**Comment by matzew** [comment]
cool - anything preventing this from being merged ? :upside_down_face:

**Comment by gbraad** [comment]
eh... Test results... ?

**Comment by gbraad** [comment]
No README ?

**Comment by jpechane** [comment]
The readme was already there - this is just an update, see https://github.com/minishift/minishift-addons/blob/master/add-ons/debezium/README.md

**Comment by gbraad** [comment]
@jpechane I jus noticed...

We have been busy with a release, so attention wasn't on the addons.

**Comment by matzew** [comment]
Thanks @gbraad !

**Pull request merged**
