### PR TITLE
Workshop addon

### PR DESCRIPTION
**Pull request by jorgemoralespou**
This addon creates a workshop that can be run on minishift. The instructions are tailored for your minishift instance. This is a version of the workshop the EVG does using a Python application.

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
Done wrong

**Comment by jorgemoralespou** [comment]
This was right

**Comment by jorgemoralespou** [comment]
I know needs a README, but wanted to add the addon ASAP and move my own repo away. Will add the README as soon as I can.

**Comment by hferentschik** [comment]
Merged. I created an issue though and referenced it in the commit message.

**Pull request closed without merging**
